files:
  /etc/nginx/conf.d/laravel.conf:
    mode: "000644"
    owner: root
    group: root
    content: |
      # Laravel routing configuration
      location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
      }

      # Remove trailing slash from non-directories
      if (!-d $request_filename) {
        rewrite ^/(.+)/$ /$1 permanent;
      }

      # Rewrite requests to index.php if file/dir doesn't exist
      if (!-e $request_filename) {
        rewrite ^(.*)$ /index.php last;
      }

      # Ensure that only actual files and folders are processed directly
      if (!-f $request_filename) {
        if (!-d $request_filename) {
          rewrite ^(.*)$ /index.php?$query_string last;
        }
      }

container_commands:
  01_reload_nginx:
    command: "sudo service nginx reload"
