files:
  /etc/nginx/conf.d/php_fpm.conf:
    mode: "000644"
    owner: root
    group: root
    content: |
      upstream php-fpm {
        server 127.0.0.1:9000;
        keepalive 32;
      }

container_commands:
  01_reload_nginx:
    command: "sudo service nginx reload"
